name: deploy-postgres

on: 
#  push:
#    branches: 
#      - main
#    paths: 
#      - 'deploy/**'
  workflow_dispatch:

env:
    AZURE_RESOURCEGROUP_NAME: AzureDev
    SERVERNAME: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/main.bicep
          parameters: 
            administratorLogin=${{ secrets.POSTGRES_ADMIN }}
            administratorLoginPassword=${{ secrets.POSTGRES_ADMIN_PASSWD }}  
            serverName=${{ env.SERVERNAME }}            